# Generated by Django 4.2.7 on 2026-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='doctor_degree',
            new_name='passport_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='languages',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('employee', 'کارمند'), ('agent', 'عامل'), ('student', 'دانشجو')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, help_text='نوع تخصص: نوشتن رساله، ترجمه، تلخیص و غیره', max_length=100, null=True),
        ),
    ]
