# Generated by Django 4.2.7 on 2026-01-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('system_password', models.CharField(blank=True, max_length=100)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, choices=[('ارشد', 'کارشناسی ارشد'), ('عاملا', 'عاملا')], max_length=20)),
                ('interest', models.TextField(blank=True)),
                ('order_type', models.CharField(blank=True, max_length=50)),
                ('committee_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('در انتظار', 'در انتظار'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('تایید شده', 'تایید شده'), ('نیاز به اصلاح', 'نیاز به اصلاح'), ('رد شده', 'رد شده')], max_length=50)),
                ('irandoc_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('در انتظار', 'در انتظار'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('تایید شده', 'تایید شده'), ('نیاز به اصلاح', 'نیاز به اصلاح'), ('رد شده', 'رد شده')], max_length=50)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('assigned_writer', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('admin_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('در انتظار', 'در انتظار'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('تایید شده', 'تایید شده'), ('نیاز به اصلاح', 'نیاز به اصلاح'), ('رد شده', 'رد شده')], max_length=50)),
                ('typing_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('در انتظار', 'در انتظار'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('تایید شده', 'تایید شده'), ('نیاز به اصلاح', 'نیاز به اصلاح'), ('رد شده', 'رد شده')], max_length=50)),
                ('summary_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('در انتظار', 'در انتظار'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('تایید شده', 'تایید شده'), ('نیاز به اصلاح', 'نیاز به اصلاح'), ('رد شده', 'رد شده')], max_length=50)),
                ('peer_review_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('در انتظار', 'در انتظار'), ('در حال انجام', 'در حال انجام'), ('تکمیل شده', 'تکمیل شده'), ('تایید شده', 'تایید شده'), ('نیاز به اصلاح', 'نیاز به اصلاح'), ('رد شده', 'رد شده')], max_length=50)),
                ('article1_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('شروع نشده', 'شروع نشده'), ('در حال نوشتن', 'در حال نوشتن'), ('ارسال شده', 'ارسال شده'), ('پذیرش شده', 'پذیرش شده')], max_length=50)),
                ('article2_status', models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('شروع نشده', 'شروع نشده'), ('در حال نوشتن', 'در حال نوشتن'), ('ارسال شده', 'ارسال شده'), ('پذیرش شده', 'پذیرش شده')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل دانشجو',
                'verbose_name_plural': 'پروفایل\u200cهای دانشجویان',
            },
        ),
    ]
