# Generated by Django 4.2.7 on 2026-01-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('ارشد', 'کارشناسی ارشد'), ('عاملا', 'عاملا')], max_length=20)),
                ('type', models.CharField(choices=[('نوشتن رساله', 'نوشتن رساله'), ('نوشتن مقاله', 'نوشتن مقاله'), ('ترجمه رساله', 'ترجمه رساله'), ('تلخیص', 'تلخیص'), ('آماده\u200cسازی ارائه', 'آماده\u200cسازی ارائه'), ('تحقیق و بررسی', 'تحقیق و بررسی')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('stage', models.CharField(blank=True, max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('estimated_days', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('doctor_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manager_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('partial', 'پرداخت جزئی'), ('paid', 'پرداخت شده'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(choices=[('doctor', 'عامل'), ('employee', 'کارمند'), ('manager', 'مدیر'), ('student', 'دانشجو')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order')),
            ],
            options={
                'verbose_name': 'وظیفه سفارش',
                'verbose_name_plural': 'وظایف سفارشات',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='orders.order')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_made', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='orders.ordertask')),
            ],
            options={
                'verbose_name': 'رد سفارش',
                'verbose_name_plural': 'تاریخچه رد سفارشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
