# Generated by Django 4.2.7 on 2026-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20),
        ),
    ]
