# Generated by Django 4.2.7 on 2026-01-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'پاسپورت'), ('certificate', 'گواهینامه'), ('transcript', 'ریز نمرات'), ('photo', 'عکس شخصی'), ('other', 'سایر')], max_length=20)),
                ('file', models.FileField(upload_to=files.models.profile_file_upload_path, validators=[files.models.validate_file_type])),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سند پروفایل',
                'verbose_name_plural': 'اسناد پروفایل',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.order_file_upload_path, validators=[files.models.validate_file_type])),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('DOCX', 'Word Document'), ('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('TEXT', 'Text File'), ('OTHER', 'Other')], max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='files.orderfile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل سفارش',
                'verbose_name_plural': 'فایل\u200cهای سفارشات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='files.orderfile')),
            ],
            options={
                'verbose_name': 'لاگ دانلود فایل',
                'verbose_name_plural': 'لاگ\u200cهای دانلود فایل',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
